#!/usr/bin/env bash

echo "Setting up git commit hooks for building CSS from SASS"
ln -s .hooks/pre-commit .git/hooks/
ln -s .hooks/post-commit .git/hooks/
echo "done."

# check for SASS command
command -v sass >/dev/null 2>&1 || { echo >&2 "This Hugo theme requires 'sass' but it's not installed. Go to http://sass-lang.com/install and get it installed"; }